name: Trigger auto deployment for sniper-bot

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/sniper-bot-AutoDeployTrigger-a8314c5b-6f04-4655-aa82-bf0f579ae6f8.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: xciledregistry.azurecr.io
          username: ${{ secrets.SNIPERBOT_REGISTRY_USERNAME }}
          password: ${{ secrets.SNIPERBOT_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: xciledregistry.azurecr.io/sniper-bot:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.SNIPERBOT_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n sniper-bot -g Xciled-Instances --server xciledregistry.azurecr.io --username  ${{ secrets.SNIPERBOT_REGISTRY_USERNAME }} --password ${{ secrets.SNIPERBOT_REGISTRY_PASSWORD }}
            az containerapp update -n sniper-bot -g Xciled-Instances --image xciledregistry.azurecr.io/sniper-bot:${{ github.sha }}
